#!/bin/bash

if iptables --new-chain LOGDROP ; then
  iptables --append LOGDROP --jump LOG
  iptables --append LOGDROP --jump DROP
fi

iptables --insert INPUT --source ${1} --protocol tcp --dport 22 --jump LOGDROP

exit 0
