#!/bin/bash

exitStatus=0

if [ ${#} -ge 1 ]
then
  script="${0}"
  directoryName="${1}"
  indent="${2}"
  echo "${indent}Start ${directoryName}"
  pushd "${directoryName}" > /dev/null 2>&1

  for directoryNameOld in *
  do
    if [ ${exitStatus} -eq 0 ]
    then
      if [ -d "${directoryNameOld}" ]
      then
        "${script}" "${directoryNameOld}" "${indent}  "
        exitStatus=${?}

        directoryNameNew=`tr '[:upper:]' '[:lower:]' <<< ${directoryNameOld}`

        if [ "${directoryNameOld}" != "${directoryNameNew}" ]
        then
          if [ -d "$directoryNameNew" ]
          then




            echo "${indent}${directoryNameNew} already exists"

          elif [ -f "$directoryNameNew" ]
          then
            echo "${indent}${directoryNameNew} already exists and is a file"
          elif ! mv --backup=numbered --verbose -- "${directoryNameOld}" "${directoryNameNew}"
          then
            echo "${indent}Could not rename ${directoryNameOld} to ${directoryNameNew}"
            exitStatus=2
          fi
        fi
      fi
    fi
  done





  popd > /dev/null 2>&1
  echo "${indent}Finish ${directoryName}"
else
  echo "${indent}Must supply directory"
  exitStatus=1
fi

exit ${exitStatus}
