#!/bin/bash

exitStatus=0

if [ ${#} -ge 1 ]
then
  script="${0}"
  directoryName="${1}"
  indent="${2}"
  echo "${indent}Start ${directoryName}"
  pushd "${directoryName}" > /dev/null 2>&1

  for fileNameOld in *
  do
    if [ ${exitStatus} -eq 0 ]
    then
      if [ -f "${fileNameOld}" ]
      then



        fileNameNew=`tr '[:upper:]' '[:lower:]' <<< ${fileNameOld}`

        if [ "${fileNameOld}" != "${fileNameNew}" ]
        then
          if [ -f "${fileNameNew}" ]
          then
            if diff -q "${fileNameOld}" "${fileNameNew}"
            then
              rm --force --verbose "${fileNameOld}"
            else
              echo "${indent}${fileNameNew} already exists"
            fi
          elif [ -d "${fileNameNew}" ]
          then
            echo "${indent}${fileNameNew} already exists and is a directory"
          elif ! mv --backup=numbered --verbose -- "${fileNameOld}" "${fileNameNew}"
          then
            echo "${indent}Could not rename ${fileNameOld} to ${fileNameNew}"
            exitStatus=2
          fi
        fi
      elif [ -d "${fileNameOld}" ]
      then
        "${script}" "${fileNameOld}" "${indent}  "
        exitStatus=${?}
      fi
    fi
  done

  popd > /dev/null 2>&1
  echo "${indent}Finish ${directoryName}"
else
  echo "${indent}Must supply directory"
  exitStatus=1
fi

exit ${exitStatus}
