#!/bin/bash
# At the time of writing, the first (and only?) argument supplied to an 'on mount' command by Gnome (or something else?) is the
# directory where the removable storage was mounted (the mount point). That suits me...

function fixFromDirectory()
{
  case "${1}" in
    (\'*\')
      echo ${1:1:((${#1}-2))}
      ;;
    (\'*)
      echo ${1:1:((${#1}-1))}
      ;;
    (*\')
      echo ${1:0:((${#1}-1))}
      ;;
    (*)
      echo ${1}
      ;;
  esac
}

readonly BASE=`basename "${0}"`
readonly fromDirectory=`fixFromDirectory "${1}"`

if pushd "${fromDirectory}"
then
  if [ -f ${BASE}.conf ]
  then
    readonly CONFIGURATION=${BASE}.conf
  else
    readonly CONFIGURATION="${HOME}/${BASE}.conf"
  fi

  if [ -f "${CONFIGURATION}" ]
  then
    while read patternLine
    do
      case "${patternLine}" in
        (importPattern=*)
          echo Importing photographs
          importPattern=${patternLine:14}
          find . -ipath "./${importPattern}" -type f -print0 | xargs -0 --no-run-if-empty import-photographs ${HOME}/Image/Photographs
          ;;
        (deletePattern=*)
          echo Deleting photographs
          deletePattern=${patternLine:14}
          find . -ipath "./${deletePattern}" -type f -print0 | xargs -0 --no-run-if-empty rm --force --verbose
          ;;
        (\#*)
          echo Comment: ${patternLine:2}
          ;;
        (*)
          echo Unimplemented pattern directive ${patternLine}
          ;;
      esac
    done < "${CONFIGURATION}"
  fi

  popd
fi

exit 0

# ---
#  Some code which might help diagnose problems
# ---

echo ${#} > /tmp/i.i
echo ${0} >> /tmp/i.i
while [ ${#} -ge 1 ]
do
  echo ${1} >> /tmp/i.i
  shift
done
pwd >> /tmp/i.i
echo "${fromDirectory}" >> /tmp/i.i
exit 0
