#!/bin/bash

exitStatus=1

if [ -f "${1}" ] ; then
  if [ -f "${2}" ] ; then
    if diff --brief --report-identical-files "${1}" "${2}" ; then
      touch --reference="${1}" "${2}"
      rm --force --verbose "${1}"
      exitStatus=${?}
    fi
  elif [ -e "${2}" ] ; then
    echo ${2} is a`file "${2}" | cut --delimiter=: --fields=2-`
  else
    mv --force --verbose "${1}" "${2}"
    exitStatus=${?}
  fi
else
  echo ${1} is a`file "${1}" | cut --delimiter=: --fields=2-`
fi

exit ${exitStatus}
