#!/bin/bash

directories=false
files=false
lower=false
symbolicLinks=false
upper=false

while getopts :dflsu option  ; do
  case ${option} in
    d)
      directories=true
      ;;
    f)
      files=true
      ;;
    l)
      lower=true
      upper=false
      ;;
    s)
      symbolicLinks=true
      ;;
    u)
      lower=false
      upper=true
      ;;
  esac
done

if ${lower} || ${upper} ; then
  if ${directories} ; then
    types='-type d'
  fi

  if ${files} ; then
    if [ "${types}" ] ; then
      types="${types} -o -type f"
    else
      types='-type f'
    fi
  fi

  if ${symbolicLinks} ; then
    if [ "${types}" ] ; then
      types="${types} -o -type l"
    else
      types='-type l'
    fi
  fi

  if [ "${types}" ] ; then
    shift $((OPTIND-1))

    argument="${1:-.}"

    find ${argument} -depth ${types} | while read pathName ; do
      nameFrom=`basename "${pathName}"`

      if ${lower} ; then
        nameTo="${nameFrom,,}"
      elif ${upper} ; then
        nameTo="${nameFrom^^}"
      else
        nameTo="${nameFrom}"
      fi

      if [ "${nameFrom}" != "${nameTo}" ] ; then
        path=`dirname "${pathName}"`

        if [ -e "${path}/${nameTo}" ] ; then
          echo nameTo \[${path}/${nameTo}\] exists
        else
          mv --no-clobber --verbose "${path}/${nameFrom}" "${path}/${nameTo}"
        fi
      fi
    done
  else
    echo TODO You must specify -d OR -f OR -s
  fi
else
  echo TODO You must specify -l xor -u
fi

exit 0
