#!/bin/bash

if [ ${#} -ge 1 ] ; then
  while [ ${#} -ge 1 ] ; do
    if [ -f "${1}" ] ; then
      clear
      echo Playing "${1}"
      # gnome-mplayer "${1}"
      mplayer -ao pulse -vo xv "${1}"
      # vlc "${1}"
      rm --interactive=always "${1}"
    elif [ -d "${1}" ] ; then
      pushd "${1}"
      ${0}
      popd
    fi

    shift
  done
else
  for extension in 3gp asf avi f4v flv m2ts mov mp4 mpeg mpg wmv ; do
    # for videoFile in *.${extension} ; do
      # ${0} "${videoFile}"
    # done
    ${0} *.${extension}
  done

  # find . -maxdepth 1 -type f \( -iname \*.3gp -o -iname \*.avi -o -iname \*.flv -o -iname \*.m2ts -o -iname \*.mov -o -iname \*.mp4 -o -iname \*.mp\*g -o -iname \*.wmv \) ! -empty -exec ${0} {} +
fi

exit 0
