#!/bin/bash

readonly OUTPUT_DIRECTORIES=Erase\ Query\ Verify

find ${OUTPUT_DIRECTORIES} -delete
mkdir ${OUTPUT_DIRECTORIES}

rpm --query --all --queryformat "%{NAME}-%{VERSION}-%{RELEASE}.%{ARCH}\n" | grep --invert-match ".(none)$" | sort --unique | while read package
do
  echo Checking package ${package}
  rpm --erase --test ${package} > Erase/${package} 2>&1
  rpm --verify --nomtime ${package} 2>&1 | grep --extended-regexp --invert-match "^(prelink:|S.\?......) " > Verify/${package}
  rpm --query --queryformat "[%{FILEMODES:perms} %{FILEUSERNAME} %{FILEGROUPNAME} %{FILENAMES} -> %{FILELINKTOS}\n]" ${package} > Query/${package} 2>&1
done

find ${OUTPUT_DIRECTORIES} -type f -empty -delete

echo Checked all packages

exit 0



rpm --query --all --queryformat "[%{FILEMODES:perms} %{FILEUSERNAME} %{FILEGROUPNAME} %{FILENAMES} -> %{FILELINKTOS}\n]" > rpm-query.output

fgrep -v "S.?...... " net-snmp-5.7.1-2.fc16.x86_64
