#!/bin/bash
#  Make a list of all the packages installed on a system, then work out which
#  are required (by other packages) and which are not. Note that this isn't
#  clever enough to work out mutually dependent, but otherwise unwanted,
#  packages.
#
outputFileBase="rpm-leaves.output"
/bin/rm --force ${outputFileBase} ${outputFileBase}.keep ${outputFileBase}.lose
/bin/rpm --query --all --queryformat "%{NAME}-%{VERSION}-%{RELEASE}.%{ARCH}\n" | /bin/sort -u > ${outputFileBase}
while read havePackage; do
  /bin/rpm --erase --test "${havePackage}"
  if [ $? -eq 0 ]; then
    outputFile=${outputFileBase}.lose
  else
    outputFile=${outputFileBase}.keep
  fi
  /bin/echo "${havePackage}" >> ${outputFile}
done < ${outputFileBase}
/usr/bin/wc -l ${outputFileBase}.keep ${outputFileBase}.lose ${outputFileBase}

exit 0
