#!/bin/bash

if pushd ${HOME} ; then
  readonly IMAGE_PHOTOGRAPHS=Image/Photographs
  readonly SHARED=Shared

  find ${IMAGE_PHOTOGRAPHS} -type f \( -name \*.bmp -o -name \*.jpeg -o -name \*.jpg -o -name \*.png \) -exec share-one-image-photographs "{}" "${SHARED}/{}" \;

  if pushd ${IMAGE_PHOTOGRAPHS} ; then
    find . | sort | uniq > ${HOME}/image-photographs.list
    popd

    if pushd ${SHARED}/${IMAGE_PHOTOGRAPHS} ; then
      find . | sort | uniq > ${HOME}/shared-image-photographs.list
      popd

      diff image-photographs.list shared-image-photographs.list | grep "^> ./" | cut --characters=5- | while read orphanedFile ; do
        orphanedPath="${SHARED}/${IMAGE_PHOTOGRAPHS}/${orphanedFile}"
        echo Orphaned path: ${orphanedPath}

        if [ -d "${orphanedPath}" ] ; then
          rm -frv "${orphanedPath}"
        else
          rm -fv "${orphanedPath}"
        fi
      done
    fi
  fi

  popd
fi

exit 0
