#!/bin/bash

script="${0}"
from="${1}"
to="${2}"

toDirectory=`dirname "${to}"`

if [ ! -d "${toDirectory}" ]
then
  mkdir -pv "${toDirectory}"
fi

if [ "${script}" -nt "${to}" ] || [ "${from}" -nt "${to}" ]
then
  # Resize images to a Facebook friendly size
  gm convert -auto-orient -geometry 720x720 -strip "${from}" "${to}"
  # Copy EXIF, since GraphicsMagick doesn't
  jhead -te "${from}" "${to}"
fi

exit 0
